#!/bin/bash

sed -i '\/application\/x-shockwave-flash=/c\application\/x-shockwave-flash=flashplayer-sa.desktop' \
/usr/share/applications/defaults.list
xdg-mime default flashplayer-sa.desktop application/x-shockwave-flash

# Get Names of users
cat /etc/passwd | grep '/home/' | \
grep -v 'cups\|syslog' | cut -d ':' -f 1 > /tmp/homes.list

function runByUsers {
	# $1 is default folder of user
	# $2 is name of user

	if [ ! -f $1/.local/share/applications/mimeapps.list ]; then
		runuser -l $2 -c "mkdir -p $1/.local/share/applications/"
		cat << EOF > $1/.local/share/applications/mimeapps.list
[Default Applications]
application/x-shockwave-flash=flashplayer-sa.desktop
EOF
	else
		if [ "$(cat $1/.local/share/applications/mimeapps.list | grep "Default Applications" | wc -l)" == "0" ]; then
			echo "[Default Applications]" >> $1/.local/share/applications/mimeapps.list
		fi
		if [ "$(cat $1/.local/share/applications/mimeapps.list | grep "x-shockwave-flash" | wc -l)" == "0" ]; then
			echo "application/x-shockwave-flash=flashplayer-sa.desktop" >> $1/.local/share/applications/mimeapps.list 
		else
			sed -i '\/application\/x-shockwave-flash=/c\application\/x-shockwave-flash=flashplayer-sa.desktop' \
			$1/.local/share/applications/mimeapps.list
		fi
	fi

	chmod 755 $1/.local/share/applications/mimeapps.list
	chown $2.$2 $1/.local/share/applications/mimeapps.list

	if [ -f /usr/bin/lxpanelctl ]; then
		su - $2 -c "lxpanelctl restart"
	fi
}

while read USUARIO; do
	runByUsers "/home/$USUARIO" "$USUARIO"
done < /tmp/homes.list
runByUsers "/etc/skel" "root"